version = 0.1

[default.deploy.parameters]
stack_name = "route-stack"
resolve_s3 = true
s3_prefix = "route-stack"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
